version: '3.8'

services:
  nodejs-vanila-app:
    image: node:23
    working_dir: /app_vanila
    env_file:
      - env/.env
    volumes:
      - ./languages/javascript:/app_vanila
    command: ["sh", "-c", "npm install -f && node vanila.js"]
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "1"

  nodejs-fastify-app:
    image: node:23
    working_dir: /app_fastify
    env_file:
      - env/.env
    volumes:
      - ./languages/javascript:/app_fastify
    command: ["sh", "-c", "npm install -f && node fastify.js"]
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: "1"

  nodejs-express-app:
    image: node:23
    working_dir: /app_express
    env_file:
      - env/.env
    volumes:
      - ./languages/javascript:/app_express
    command: ["sh", "-c", "npm install -f && node fastify.js"]
    ports:
      - "3002:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
  
  bun-vanila-app:
    image: oven/bun
    working_dir: /app
    env_file:
      - env/.env
    volumes:
      - ./languages/javascript:/app
    command: ["sh", "-c", "bun install -f && bun run vanila.js"]
    ports:
      - "3003:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
    networks:
      - research-network

networks:
  research-network:
    driver: bridge