version: '3.8'

services:
  nodejs-vanila-app:
    image: node:23
    working_dir: /app
    env_file:
      - env/.env
    volumes:
      - ./javascript:/app
    command: ["sh", "-c", "npm install && node vanila.js"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nodejs-fastify-app:
    image: node:23
    working_dir: /app
    env_file:
      - env/.env
    volumes:
      - ./javascript:/app
    command: ["sh", "-c", "npm install && node fastify.js"]
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "1"

  nodejs-express-app:
    image: node:23
    working_dir: /app
    env_file:
      - env/.env
    volumes:
      - ./javascript:/app
    command: ["sh", "-c", "npm install && node fastify.js"]
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "1"
  
  bun-vanila-app:
    image: oven/bun
    working_dir: /app
    env_file:
      - env/.env
    volumes:
      - ./javascript:/app
    command: ["sh", "-c", "bun install && bun run vanila.js"]
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "1"
    networks:
      - research-network

networks:
  research-network:
    driver: bridge